import { FormEvent, StrictMode, useEffect, useState } from "react";
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import { createRoot } from "react-dom/client";
import "./styles/index.css";

const api = import.meta.env.VITE_API_URL ?? "http://localhost:8000/api/v1";
const token = () => localStorage.getItem("accessToken");
const request = (path: string, options: RequestInit = {}) => fetch(`${api}${path}`, { ...options, headers: { Authorization: `Bearer ${token()}`, "Content-Type": "application/json", ...options.headers } });
type Post = { id: number; title: string; content: string; status: "draft" | "published"; reading_time: number; updated_at: string };
type Comment = { id: number; comment: string; parent_comment_id: number | null; created_at: string };

function AuthPage({ register = false }: { register?: boolean }) { const navigate = useNavigate(); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch(`${api}/auth/${register ? "register" : "login"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const body = await response.json(); if (!response.ok) return setError(body.detail ?? "Unable to continue"); if (register) return navigate("/login"); localStorage.setItem("accessToken", body.access_token); navigate("/dashboard"); }
  return <main><h1>{register ? "Create account" : "Welcome back"}</h1><form onSubmit={submit}>{register && <input name="username" placeholder="Username" minLength={3} required />}<input name="email" type="email" placeholder="Email" required /><input name="password" type="password" placeholder="Password" minLength={8} required /><button>{register ? "Register" : "Sign in"}</button>{error && <p role="alert">{error}</p>}</form><p><Link to={register ? "/login" : "/register"}>{register ? "Already have an account? Sign in" : "Need an account? Register"}</Link></p></main>; }

function Guard({ children }: { children: React.ReactNode }) { return token() ? <>{children}</> : <Navigate to="/login" replace />; }
function Dashboard() { const navigate = useNavigate(); const [stats, setStats] = useState<Record<string, number> | null>(null); useEffect(() => { request("/dashboard/analytics").then(r => r.json()).then(setStats); }, []); return <main><h1>Dashboard</h1><p>Manage your writing.</p>{stats && <p>{stats.published} published · {stats.drafts} drafts · {stats.views} views · {stats.likes} likes</p>}<p><Link to="/posts/new">Write a post</Link> · <Link to="/posts/mine">My posts</Link> · <Link to="/settings">Profile settings</Link></p><button className="logout" onClick={() => { localStorage.removeItem("accessToken"); navigate("/login"); }}>Sign out</button></main>; }
function Settings() { const [profile, setProfile] = useState({ username: "", bio: "", profile_picture: "" }); const [message, setMessage] = useState(""); useEffect(() => { request("/users/profile").then(r => r.json()).then(p => setProfile({ username: p.username ?? "", bio: p.bio ?? "", profile_picture: p.profile_picture ?? "" })); }, []); async function save(e: FormEvent) { e.preventDefault(); const response = await request("/users/profile", { method: "PUT", body: JSON.stringify(profile) }); setMessage(response.ok ? "Profile updated." : "Unable to update profile."); } return <main><h1>Profile settings</h1><form onSubmit={save}><input value={profile.username} onChange={e => setProfile({ ...profile, username: e.target.value })} placeholder="Username" required /><textarea value={profile.bio} onChange={e => setProfile({ ...profile, bio: e.target.value })} placeholder="Bio" /><input value={profile.profile_picture} onChange={e => setProfile({ ...profile, profile_picture: e.target.value })} placeholder="Profile image URL" /><button>Save changes</button></form><p>{message}</p><Link to="/dashboard">Back to dashboard</Link></main>; }
function Admin() { const [stats, setStats] = useState<Record<string, number> | null>(null); const [name, setName] = useState(""); const [message, setMessage] = useState(""); useEffect(() => { request("/admin/analytics").then(r => r.ok ? r.json() : null).then(setStats); }, []); async function create(e: FormEvent) { e.preventDefault(); const r = await request("/admin/categories", { method: "POST", body: JSON.stringify({ name }) }); setMessage(r.ok ? "Category created." : "Admin access is required."); setName(""); } if (!stats) return <main><p>Admin access is required.</p><Link to="/dashboard">Back</Link></main>; return <main><h1>Admin dashboard</h1><p>{stats.users} users · {stats.posts} posts · {stats.comments} comments · {stats.likes} likes · {stats.views} views</p><form onSubmit={create}><input value={name} onChange={e => setName(e.target.value)} placeholder="New category" required /><button>Add category</button></form><p>{message}</p><Link to="/dashboard">Back</Link></main>; }

function Editor() { const { id } = useParams(); const navigate = useNavigate(); const [post, setPost] = useState<Partial<Post>>({ title: "", content: "", status: "draft" }); const [error, setError] = useState("");
  useEffect(() => { if (id) request("/posts/mine").then(r => r.json()).then((posts: Post[]) => setPost(posts.find(p => p.id === Number(id)) ?? {})); }, [id]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const method = id ? "PUT" : "POST"; const response = await request(id ? `/posts/${id}` : "/posts", { method, body: JSON.stringify(post) }); const body = await response.json(); if (!response.ok) return setError(body.detail ?? "Unable to save"); navigate("/posts/mine"); }
  return <main><h1>{id ? "Edit post" : "Write a post"}</h1><form onSubmit={submit}><input value={post.title ?? ""} onChange={e => setPost({ ...post, title: e.target.value })} placeholder="Title" minLength={3} required /><textarea value={post.content ?? ""} onChange={e => setPost({ ...post, content: e.target.value })} placeholder="Start writing…" required rows={14} /><select value={post.status} onChange={e => setPost({ ...post, status: e.target.value as "draft" | "published" })}><option value="draft">Save as draft</option><option value="published">Publish</option></select><button>Save post</button>{error && <p role="alert">{error}</p>}</form><p><Link to="/posts/mine">Back to my posts</Link></p></main>; }

function MyPosts() { const [posts, setPosts] = useState<Post[]>([]); const load = () => request("/posts/mine").then(r => r.json()).then(setPosts); useEffect(() => { void load(); }, []);
  async function remove(id: number) { if (confirm("Delete this post?")) { await request(`/posts/${id}`, { method: "DELETE" }); load(); } }
  return <main><h1>My posts</h1><p><Link to="/posts/new">Write a post</Link></p>{posts.length === 0 ? <p>You have not written anything yet.</p> : <ul>{posts.map(post => <li key={post.id}><strong>{post.title}</strong> — {post.status} · {post.reading_time} min <Link to={`/posts/${post.id}/edit`}>Edit</Link> <button onClick={() => remove(post.id)}>Delete</button></li>)}</ul>}<p><Link to="/dashboard">Back to dashboard</Link></p></main>; }
function Explore() { const [query, setQuery] = useState(""); const [posts, setPosts] = useState<Post[]>([]); const load = (q = "") => fetch(`${api}${q ? `/search?q=${encodeURIComponent(q)}` : "/posts"}`).then(r => r.ok ? r.json() : []).then(setPosts); useEffect(() => { void load(); }, []); const samples = [{ title: "The Art of a Slower Morning", note: "Small rituals for making space before the day begins.", tag: "Wellbeing" }, { title: "Notes From a Train Window", note: "A quiet essay on movement, memory, and the scenery between.", tag: "Travel" }, { title: "How to Keep a Reading Life", note: "A gentle approach to choosing books and staying curious.", tag: "Culture" }, { title: "The Garden in Late Summer", note: "What tending a small garden teaches us about patience.", tag: "Lifestyle" }]; return <><main className="hero"><p className="eyebrow">A place for thoughtful writing</p><h1>Paper &amp; Bloom</h1><p className="intro">Read, write, and gather around stories worth lingering over—ideas on culture, life, and the everyday.</p><a className="scroll-cue" href="#explore">Explore the journal ↓</a></main><main className="explore-section" id="explore"><p className="eyebrow">Find your next read</p><h2>Explore stories</h2><form onSubmit={e => { e.preventDefault(); void load(query); }}><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search for a blog" /><button>Search</button></form>{posts.length > 0 && <ul>{posts.map(p => <li key={p.id}><Link to={`/posts/${p.id}`}><strong>{p.title}</strong></Link> — {p.reading_time} min read</li>)}</ul>}<section className="sample-grid">{samples.map((sample, index) => <article className="sample-card" key={sample.title}><span>{sample.tag}</span><h2>{sample.title}</h2><p>{sample.note}</p><Link to={token() ? `/sample/${index}` : "/login"}>Read story →</Link></article>)}</section>{!token() && <p><Link to="/login">Sign in</Link> · <Link to="/register">Create an account</Link></p>}</main></>; }
function PostDetail() { const { id } = useParams(); const [post, setPost] = useState<Post | null>(null); const [comments, setComments] = useState<Comment[]>([]); const [text, setText] = useState(""); const load = () => { fetch(`${api}/posts/${id}`).then(r => r.ok ? r.json() : null).then(setPost); fetch(`${api}/posts/${id}/comments`).then(r => r.json()).then(setComments); }; useEffect(() => { load(); }, [id]); async function submit(e: FormEvent) { e.preventDefault(); if (!token()) return alert("Sign in to comment."); const r = await request(`/posts/${id}/comments`, { method: "POST", body: JSON.stringify({ comment: text }) }); if (r.ok) { setText(""); load(); } } if (!post) return <main><p>Loading post…</p></main>; return <main><p><Link to="/">Explore</Link></p><article><h1>{post.title}</h1><p>{post.reading_time} min read</p><p>{post.content}</p></article><section><h2>Comments</h2><form onSubmit={submit}><textarea value={text} onChange={e => setText(e.target.value)} placeholder="Join the conversation" required /><button>Comment</button></form>{comments.length ? <ul>{comments.map(c => <li key={c.id}>{c.comment}</li>)}</ul> : <p>No comments yet.</p>}</section></main>; }
function SampleStory() { const { id } = useParams(); const stories = ["Begin with a quiet cup, a window, and one small thing that belongs only to you. A slower morning is not a perfect ritual—it is permission to arrive before the day starts asking for you.", "A train window turns every journey into a moving frame. Fields, towns, and strangers slide past, leaving us with the rare pleasure of being between one place and another.", "A reading life grows from curiosity, not completion. Keep a book nearby, follow an unexpected footnote, and let the next title find you slowly.", "Late summer asks us to notice what is still becoming. In the garden, patient tending leaves room for surprise—one final bloom, one new green shoot."]; return <main><p><Link to="/">Explore</Link></p><article><h1>Paper &amp; Bloom Journal</h1><p>{stories[Number(id)] ?? stories[0]}</p></article></main>; }
function OurStory() { return <main className="story"><p className="eyebrow">Our story</p><h1>Words deserve room to bloom.</h1><p>Paper &amp; Bloom began with a simple thought: some of the most beautiful ideas start as words on paper.</p><p>We’ve all had moments when we wanted to write something—a memory that made us smile, a lesson learned the hard way, a recipe passed down through generations, a travel story, or just a random thought that deserved more than disappearing into the notes app.</p><p>But sharing those stories wasn’t always easy. Social media often rewards speed over substance, and thoughtful writing gets lost in endless scrolling.</p><p>So we imagined a little corner of the internet where words could breathe.</p><p>A place where stories could bloom.</p><p>That’s how <strong>Paper &amp; Bloom</strong> came to life.</p><p>The name reflects what we believe. Every meaningful story starts as a blank page—a piece of paper waiting for someone’s voice. And once it’s shared, it has the power to bloom into inspiration, comfort, curiosity, or connection for someone else.</p><p>Whether you’re writing your very first blog or your hundredth, this is a space where your experiences matter. There are no perfect stories here—only honest ones. The kind that make us laugh, teach us something new, remind us we’re not alone, or encourage us to see the world a little differently.</p><p>Paper &amp; Bloom is more than a blogging platform. It’s a growing collection of voices, ideas, and moments that deserve to be remembered.</p><p>Thank you for adding your story to ours.</p><p>We’re so glad you’re here.</p></main>; }
function Contact() { const [message, setMessage] = useState(""); const [sent, setSent] = useState(false); return <main className="story"><p className="eyebrow">Contact</p><h1>Drop us a Little Note :) </h1><p>Every friendship starts with a hello.</p><p>Whether you’re here to collaborate, share your thoughts, ask a question, or simply introduce yourself, we’d be delighted to hear from you.</p><p>Our inbox is always open, and we can’t wait to meet you.</p><form onSubmit={e => { e.preventDefault(); setSent(true); setMessage(""); }}><textarea value={message} onChange={e => setMessage(e.target.value)} placeholder="Write your message here…" required /><button>Send note</button></form>{sent && <p className="sent">Thank you—your note has been received.</p>}</main>; }
function Navbar() { const location = useLocation(); const signedIn = Boolean(token()); return <nav>{location.pathname !== "/" ? <Link className="brand" to="/">Paper &amp; Bloom</Link> : <span />}<div><Link to="/">Home</Link><Link to="/our-story">Our story</Link><Link to="/contact">Contact</Link>{signedIn ? <Link to="/dashboard">Dashboard</Link> : <Link to="/login">Sign in</Link>}</div></nav>; }
function Footer() { return <footer><div><strong>Paper &amp; Bloom</strong><p>A quieter place for stories, ideas, and moments worth remembering.</p></div><div className="footer-links"><Link to="/">Home</Link><Link to="/our-story">Our story</Link><Link to="/contact">Contact</Link></div><small>© 2026 Paper &amp; Bloom. Made for stories that bloom.</small></footer>; }
function App() { return <><Navbar /><Routes><Route path="/" element={<Explore />} /><Route path="/our-story" element={<OurStory />} /><Route path="/contact" element={<Contact />} /><Route path="/login" element={<AuthPage />} /><Route path="/register" element={<AuthPage register />} /><Route path="/dashboard" element={<Guard><Dashboard /></Guard>} /><Route path="/admin" element={<Guard><Admin /></Guard>} /><Route path="/settings" element={<Guard><Settings /></Guard>} /><Route path="/sample/:id" element={<Guard><SampleStory /></Guard>} /><Route path="/posts/new" element={<Guard><Editor /></Guard>} /><Route path="/posts/mine" element={<Guard><MyPosts /></Guard>} /><Route path="/posts/:id/edit" element={<Guard><Editor /></Guard>} /><Route path="/posts/:id" element={<PostDetail />} /></Routes><Footer /></>; }
createRoot(document.getElementById("root")!).render(<StrictMode><BrowserRouter><App /></BrowserRouter></StrictMode>);
