import { FormEvent, StrictMode, useEffect, useState } from "react";
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { createRoot } from "react-dom/client";
import "./styles/index.css";

const api = "http://localhost:8000/api/v1";
const token = () => localStorage.getItem("accessToken");
const request = (path: string, options: RequestInit = {}) => fetch(`${api}${path}`, { ...options, headers: { Authorization: `Bearer ${token()}`, "Content-Type": "application/json", ...options.headers } });
type Post = { id: number; title: string; content: string; status: "draft" | "published"; reading_time: number; updated_at: string };
type Comment = { id: number; comment: string; parent_comment_id: number | null; created_at: string };

function AuthPage({ register = false }: { register?: boolean }) { const navigate = useNavigate(); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch(`${api}/auth/${register ? "register" : "login"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const body = await response.json(); if (!response.ok) return setError(body.detail ?? "Unable to continue"); if (register) return navigate("/login"); localStorage.setItem("accessToken", body.access_token); navigate("/dashboard"); }
  return <main><h1>{register ? "Create account" : "Welcome back"}</h1><form onSubmit={submit}>{register && <input name="username" placeholder="Username" minLength={3} required />}<input name="email" type="email" placeholder="Email" required /><input name="password" type="password" placeholder="Password" minLength={8} required /><button>{register ? "Register" : "Sign in"}</button>{error && <p role="alert">{error}</p>}</form><p><Link to={register ? "/login" : "/register"}>{register ? "Already have an account? Sign in" : "Need an account? Register"}</Link></p></main>; }

function Guard({ children }: { children: React.ReactNode }) { return token() ? <>{children}</> : <Navigate to="/login" replace />; }
function Dashboard() { const navigate = useNavigate(); const [stats, setStats] = useState<Record<string, number> | null>(null); useEffect(() => { request("/dashboard/analytics").then(r => r.json()).then(setStats); }, []); return <main><h1>Dashboard</h1><p>Manage your writing.</p>{stats && <p>{stats.published} published · {stats.drafts} drafts · {stats.views} views · {stats.likes} likes</p>}<p><Link to="/posts/new">Write a post</Link> · <Link to="/posts/mine">My posts</Link> · <Link to="/settings">Profile settings</Link></p><button onClick={() => { localStorage.removeItem("accessToken"); navigate("/login"); }}>Sign out</button></main>; }
function Settings() { const [profile, setProfile] = useState({ username: "", bio: "", profile_picture: "" }); const [message, setMessage] = useState(""); useEffect(() => { request("/users/profile").then(r => r.json()).then(p => setProfile({ username: p.username ?? "", bio: p.bio ?? "", profile_picture: p.profile_picture ?? "" })); }, []); async function save(e: FormEvent) { e.preventDefault(); const response = await request("/users/profile", { method: "PUT", body: JSON.stringify(profile) }); setMessage(response.ok ? "Profile updated." : "Unable to update profile."); } return <main><h1>Profile settings</h1><form onSubmit={save}><input value={profile.username} onChange={e => setProfile({ ...profile, username: e.target.value })} placeholder="Username" required /><textarea value={profile.bio} onChange={e => setProfile({ ...profile, bio: e.target.value })} placeholder="Bio" /><input value={profile.profile_picture} onChange={e => setProfile({ ...profile, profile_picture: e.target.value })} placeholder="Profile image URL" /><button>Save changes</button></form><p>{message}</p><Link to="/dashboard">Back to dashboard</Link></main>; }

function Editor() { const { id } = useParams(); const navigate = useNavigate(); const [post, setPost] = useState<Partial<Post>>({ title: "", content: "", status: "draft" }); const [error, setError] = useState("");
  useEffect(() => { if (id) request("/posts/mine").then(r => r.json()).then((posts: Post[]) => setPost(posts.find(p => p.id === Number(id)) ?? {})); }, [id]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const method = id ? "PUT" : "POST"; const response = await request(id ? `/posts/${id}` : "/posts", { method, body: JSON.stringify(post) }); const body = await response.json(); if (!response.ok) return setError(body.detail ?? "Unable to save"); navigate("/posts/mine"); }
  return <main><h1>{id ? "Edit post" : "Write a post"}</h1><form onSubmit={submit}><input value={post.title ?? ""} onChange={e => setPost({ ...post, title: e.target.value })} placeholder="Title" minLength={3} required /><textarea value={post.content ?? ""} onChange={e => setPost({ ...post, content: e.target.value })} placeholder="Start writing…" required rows={14} /><select value={post.status} onChange={e => setPost({ ...post, status: e.target.value as "draft" | "published" })}><option value="draft">Save as draft</option><option value="published">Publish</option></select><button>Save post</button>{error && <p role="alert">{error}</p>}</form><p><Link to="/posts/mine">Back to my posts</Link></p></main>; }

function MyPosts() { const [posts, setPosts] = useState<Post[]>([]); const load = () => request("/posts/mine").then(r => r.json()).then(setPosts); useEffect(() => { void load(); }, []);
  async function remove(id: number) { if (confirm("Delete this post?")) { await request(`/posts/${id}`, { method: "DELETE" }); load(); } }
  return <main><h1>My posts</h1><p><Link to="/posts/new">Write a post</Link></p>{posts.length === 0 ? <p>You have not written anything yet.</p> : <ul>{posts.map(post => <li key={post.id}><strong>{post.title}</strong> — {post.status} · {post.reading_time} min <Link to={`/posts/${post.id}/edit`}>Edit</Link> <button onClick={() => remove(post.id)}>Delete</button></li>)}</ul>}<p><Link to="/dashboard">Back to dashboard</Link></p></main>; }
function Explore() { const [query, setQuery] = useState(""); const [posts, setPosts] = useState<Post[]>([]); const load = (q = "") => fetch(`${api}${q ? `/search?q=${encodeURIComponent(q)}` : "/posts"}`).then(r => r.json()).then(setPosts); useEffect(() => { void load(); }, []); const engage = (id: number, action: "likes" | "bookmarks") => { if (!token()) return alert("Sign in to interact with posts."); void request(`/posts/${id}/${action}`, { method: "POST" }); }; return <main><h1>Explore</h1><form onSubmit={e => { e.preventDefault(); void load(query); }}><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search published posts" /><button>Search</button></form>{posts.length ? <ul>{posts.map(p => <li key={p.id}><Link to={`/posts/${p.id}`}><strong>{p.title}</strong></Link> — {p.reading_time} min read <button onClick={() => engage(p.id, "likes")}>Like</button> <button onClick={() => engage(p.id, "bookmarks")}>Bookmark</button></li>)}</ul> : <p>No published posts found.</p>}<p><Link to="/login">Sign in</Link></p></main>; }
function PostDetail() { const { id } = useParams(); const [post, setPost] = useState<Post | null>(null); const [comments, setComments] = useState<Comment[]>([]); const [text, setText] = useState(""); const load = () => { fetch(`${api}/posts/${id}`).then(r => r.ok ? r.json() : null).then(setPost); fetch(`${api}/posts/${id}/comments`).then(r => r.json()).then(setComments); }; useEffect(() => { load(); }, [id]); async function submit(e: FormEvent) { e.preventDefault(); if (!token()) return alert("Sign in to comment."); const r = await request(`/posts/${id}/comments`, { method: "POST", body: JSON.stringify({ comment: text }) }); if (r.ok) { setText(""); load(); } } if (!post) return <main><p>Loading post…</p></main>; return <main><p><Link to="/">Explore</Link></p><article><h1>{post.title}</h1><p>{post.reading_time} min read</p><p>{post.content}</p></article><section><h2>Comments</h2><form onSubmit={submit}><textarea value={text} onChange={e => setText(e.target.value)} placeholder="Join the conversation" required /><button>Comment</button></form>{comments.length ? <ul>{comments.map(c => <li key={c.id}>{c.comment}</li>)}</ul> : <p>No comments yet.</p>}</section></main>; }
function App() { return <Routes><Route path="/" element={<Explore />} /><Route path="/login" element={<AuthPage />} /><Route path="/register" element={<AuthPage register />} /><Route path="/dashboard" element={<Guard><Dashboard /></Guard>} /><Route path="/settings" element={<Guard><Settings /></Guard>} /><Route path="/posts/new" element={<Guard><Editor /></Guard>} /><Route path="/posts/mine" element={<Guard><MyPosts /></Guard>} /><Route path="/posts/:id/edit" element={<Guard><Editor /></Guard>} /><Route path="/posts/:id" element={<PostDetail />} /></Routes>; }
createRoot(document.getElementById("root")!).render(<StrictMode><BrowserRouter><App /></BrowserRouter></StrictMode>);
